baseURL = 'https://kanda.rec/'
languageCode = 'fr-FR'
title = 'k4ndar3c blog'
theme = 'nightfall'

[params]
author = "k4ndar3c"
user = "k4ndar3c"
hostname = "kanda.rec"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/k4ndAr3c"

[[params.social]]
key = 1
name = "email"
url = "mailto:kandarec@proton.me"

[[params.social]]
key = 2
name = "root-me"
url = "https://www.root-me.org/k4ndar3c"

[[params.social]]
key = 3
name = "ctf_team"
url = "https://ctftime.org/team/282180"

[[params.social]]
key = 4
name = "presentation"
url = "https://forum.zenk-security.com/showthread.php?tid=4690"

[[params.social]]
key = 5
name = "shellfolio"
url = "https://k4ndar3c.github.io/hugos1te/shellfolio.html"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"

  [[menu.header]]
    name = "infos"
    weight = 0
    url = "/infos"
  
  [[menu.header]]
    name = "tl;dr"
    weight = 0
    url = "/tldr"

